FROM python:3.9-slim

WORKDIR /app/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY kafka_mysql_consumer.py .
COPY mysql_handler.py .

CMD ["python", "kafka_mysql_consumer.py"]